import { useSelector } from 'react-redux';

export const translations = {
  English: {
    // Navigation / Public
    'Home': 'Home',
    'About Scholar': 'About Scholar',
    'Articles': 'Articles',
    'Fatwas': 'Fatwas',
    'Q&As': 'Q&As',
    'Publications': 'Publications',
    'Lectures': 'Lectures',
    'Events': 'Events',
    'Contact': 'Contact',
    'Ask Question': 'Ask Question',
    'Ask Q': 'Ask Q',
    'Dashboard': 'Dashboard',
    'Logout': 'Logout',
    'Admin Login': 'Admin Login',
    'Navigation': 'Navigation',
    'Switch to Light Mode': 'Switch to Light Mode',
    'Switch to Dark Mode': 'Switch to Dark Mode',

    // Branding / Titles
    'Dr. Islamic Scholar': 'Dr. Islamic Scholar',
    'Mufti & Shariah Educator': 'Mufti & Shariah Educator',
    'Mufti & Professor of Islamic Jurisprudence': 'Mufti & Professor of Islamic Jurisprudence',
    'Sheikh & Professor of Islamic Studies': 'Sheikh & Professor of Islamic Studies',
    'Mufti & Professor of Islamic Law': 'Mufti & Professor of Islamic Law',
    'Professor': 'Professor',

    // Admin Dashboard / General
    'Admin Dashboard': 'Admin Dashboard',
    'Welcome back,': 'Welcome back,',
    'Website Settings': 'Website Settings',
    'Total Articles': 'Total Articles',
    'Total Fatwas': 'Total Fatwas',
    'Total Publications': 'Total Publications',
    'Total Lectures': 'Total Lectures',
    'Total Q&As': 'Total Q&As',
    'Total Messages': 'Total Messages',
    'Total Website Visitors': 'Total Website Visitors',
    'Quick Content Operations': 'Quick Content Operations',
    'Write New Article': 'Write New Article',
    'Publish Islamic Rulings': 'Publish Islamic Rulings',
    'Add New Fatwa': 'Add New Fatwa',
    'Jurisprudence Solutions': 'Jurisprudence Solutions',
    'Review Questions': 'Review Questions',
    'Pending Inbox': 'Pending Inbox',
    'Add Publication': 'Add Publication',
    'Link Google Drive Files': 'Link Google Drive Files',
    'Pending': 'Pending',

    // Admin Sidebar & Page Titles
    'Manage Articles': 'Manage Articles',
    'Manage Fatwas': 'Manage Fatwas',
    'Manage Questions': 'Manage Questions & Answers',
    'Manage Publications': 'Manage Publications',
    'Manage Lectures': 'Manage Lectures',
    'Manage Events': 'Manage Events',
    'Manage Settings': 'Manage Settings',

    // Form controls and buttons
    'Save Configuration': 'Save Configuration',
    'Saving Settings...': 'Saving Settings...',
    'Cancel': 'Cancel',
    'Save': 'Save',
    'Write Article': 'Write Article',
    'Edit Scholarly Article': 'Edit Scholarly Article',
    'Write New Scholarly Article': 'Write New Scholarly Article',
    'Saving...': 'Saving...',
    'Save Article': 'Save Article',
    'Add Fatwa': 'Add Fatwa',
    'Edit Jurisprudence Fatwa': 'Edit Jurisprudence Fatwa',
    'Add New Jurisprudence Fatwa': 'Add New Jurisprudence Fatwa',
    'Save Fatwa': 'Save Fatwa',
    'Add Lecture': 'Add Lecture',
    'Upload New Audio/Video Lecture': 'Upload New Audio/Video Lecture',
    'Edit Lecture Details': 'Edit Lecture Details',
    'Save Lecture': 'Save Lecture',
    'Add Event': 'Add Event',
    'Create New Scholar Event': 'Create New Scholar Event',
    'Edit Scholar Event': 'Edit Scholar Event',
    'Save Event': 'Save Event',
    'Add Publication Link': 'Add Publication Link',
    'Add New Google Drive Publication': 'Add New Google Drive Publication',
    'Edit Publication Details': 'Edit Publication Details',
    'Save Publication': 'Save Publication',

    // Table headers & Labels
    'Title': 'Title',
    'Category': 'Category',
    'Publish Date': 'Publish Date',
    'Views': 'Views',
    'Actions': 'Actions',
    'Edit Article': 'Edit Article',
    'Delete Article': 'Delete Article',
    'Question Title': 'Question Title',
    'Questioner': 'Questioner',
    'Date Asked': 'Date Asked',
    'Status': 'Status',
    'Answer Question': 'Answer Question',
    'View Details': 'View Details',
    'Delete Question': 'Delete Question',
    'Language': 'Language',
    'Author': 'Author',
    'Download Link': 'Download Link',
    'Edit Publication': 'Edit Publication',
    'Delete Publication': 'Delete Publication',
    'Video/Audio URL': 'Video/Audio URL',
    'Type': 'Type',
    'Edit Lecture': 'Edit Lecture',
    'Delete Lecture': 'Delete Lecture',
    'Event Date': 'Event Date',
    'Location': 'Location',
    'Edit Event': 'Edit Event',
    'Delete Event': 'Delete Event',

    // Manage Settings tab names
    'Biography Details': 'Biography Details',
    'Contact Details': 'Contact Details',
    'Social Networks': 'Social Networks',
    'Home Page Hero': 'Home Page Hero',
    'SEO Settings': 'SEO Settings',
    'Language Settings': 'Language Settings',
    
    // Manage Settings inputs
    'Scholar Full Name': 'Scholar Full Name',
    'Honorary Islamic Title': 'Honorary Islamic Title',
    'Detailed Biography Statement': 'Detailed Biography Statement',
    'Madrasah Education': 'Madrasah Education',
    'University Education': 'University Education',
    'Qualifications (Comma Separated)': 'Qualifications (Comma Separated)',
    'Areas of Expertise (Comma Separated)': 'Areas of Expertise (Comma Separated)',
    'Teaching Experience Synopsis': 'Teaching Experience Synopsis',
    'Research Interests (Comma Separated)': 'Research Interests (Comma Separated)',
    'Associated Institutions (Comma Separated)': 'Associated Institutions (Comma Separated)',
    'Key Achievements (Comma Separated)': 'Key Achievements (Comma Separated)',
    'Office Address': 'Office Address',
    'Phone Number': 'Phone Number',
    'WhatsApp Number Link': 'WhatsApp Number Link',
    'Email Address': 'Email Address',
    'Facebook Profile URL': 'Facebook Profile URL',
    'YouTube Channel URL': 'YouTube Channel URL',
    'Twitter / X URL': 'Twitter / X URL',
    'Instagram URL': 'Instagram URL',
    'Hero Title Name': 'Hero Title Name',
    'Hero Title Designation': 'Hero Title Designation',
    'Hero Introduction Paragraph': 'Hero Introduction Paragraph',
    'Scholar Mission Statement Text': 'Scholar Mission Statement Text',
    'Default Meta Title Tag': 'Default Meta Title Tag',
    'Default Meta Description Tag': 'Default Meta Description Tag',

    // Form inputs placeholders & hints
    'Modify biography profiles, contact numbers, and SEO tags': 'Modify biography profiles, contact numbers, and SEO tags',
    'Choose default system interface language': 'Choose default system interface language',
    'Select Language': 'Select Language',
    'English': 'English',
    'Urdu': 'Urdu',
    'Save Settings': 'Save Settings',

    // Lectures additional
    'Add, update, or remove audio and video sermons': 'Add, update, or remove audio and video sermons',
    'Lecture Title *': 'Lecture Title *',
    'Media Format *': 'Media Format *',
    'Media URL (YouTube/Facebook/MP3 Link) *': 'Media URL (YouTube/Facebook/MP3 Link) *',
    'Custom Thumbnail Image URL (Optional)': 'Custom Thumbnail Image URL (Optional)',
    'Brief Description *': 'Brief Description *',
    'e.g. Purifying the Heart: The Islamic Path': 'e.g. Purifying the Heart: The Islamic Path',
    'Provide a short synopsis overview of the topics discussed in this sermon...': 'Provide a short synopsis overview of the topics discussed in this sermon...',
    'No Lectures Uploaded': 'No Lectures Uploaded',
    'Click the "Add Lecture" button to link your first bayan video/audio.': 'Click the "Add Lecture" button to link your first bayan video/audio.',
    'YouTube Videos': 'YouTube Videos',
    'Facebook Videos': 'Facebook Videos',
    'Audio Lectures': 'Audio Lectures',
    'Bayan Recordings': 'Bayan Recordings',

    // Events additional
    'Add, update, or remove scheduled programs and gatherings': 'Add, update, or remove scheduled programs and gatherings',
    'Add New Event Program': 'Add New Event Program',
    'Edit Event Details': 'Edit Event Details',
    'Event Program Title *': 'Event Program Title *',
    'Event Date & Time *': 'Event Date & Time *',
    'Program Location *': 'Program Location *',
    'Poster Image URL (Optional)': 'Poster Image URL (Optional)',
    'e.g. Halal Investment Workshop Seminar': 'e.g. Halal Investment Workshop Seminar',
    'e.g. Masjid Al-Noor, Seminar Room A': 'e.g. Masjid Al-Noor, Seminar Room A',
    'Provide details about the gathering topics, timings, registration fee if any...': 'Provide details about the gathering topics, timings, registration fee if any...',
    'No Events Scheduled': 'No Events Scheduled',
    'Click the "Add Event" button to schedule your first program.': 'Click the "Add Event" button to schedule your first program.',
  },
};

export default function useTranslate() {
  const t = (key, fallback = '') => {
    if (!key) return '';
    return translations['English']?.[key] || fallback || key;
  };

  return { t, lang: 'English', isUrdu: false };
}
