import { useSelector } from 'react-redux';

export const translations = {
  English: {
    // Navigation / Public
    'Home': 'Home',
    'About Scholar': 'About Scholar',
    'Articles': 'Articles',
    'Fatwas': 'Fatwas',
    'Q&As': 'Q&As',
    'Publications': 'Publications',
    'Lectures': 'Lectures',
    'Events': 'Events',
    'Contact': 'Contact',
    'Ask Question': 'Ask Question',
    'Ask Q': 'Ask Q',
    'Dashboard': 'Dashboard',
    'Logout': 'Logout',
    'Admin Login': 'Admin Login',
    'Navigation': 'Navigation',
    'Switch to Light Mode': 'Switch to Light Mode',
    'Switch to Dark Mode': 'Switch to Dark Mode',

    // Branding / Titles
    'Dr. Islamic Scholar': 'Dr. Islamic Scholar',
    'Mufti & Shariah Educator': 'Mufti & Shariah Educator',
    'Mufti & Professor of Islamic Jurisprudence': 'Mufti & Professor of Islamic Jurisprudence',
    'Sheikh & Professor of Islamic Studies': 'Sheikh & Professor of Islamic Studies',
    'Mufti & Professor of Islamic Law': 'Mufti & Professor of Islamic Law',
    'Professor': 'Professor',

    // Admin Dashboard / General
    'Admin Dashboard': 'Admin Dashboard',
    'Welcome back,': 'Welcome back,',
    'Website Settings': 'Website Settings',
    'Total Articles': 'Total Articles',
    'Total Fatwas': 'Total Fatwas',
    'Total Publications': 'Total Publications',
    'Total Lectures': 'Total Lectures',
    'Total Q&As': 'Total Q&As',
    'Total Messages': 'Total Messages',
    'Total Website Visitors': 'Total Website Visitors',
    'Quick Content Operations': 'Quick Content Operations',
    'Write New Article': 'Write New Article',
    'Publish Islamic Rulings': 'Publish Islamic Rulings',
    'Add New Fatwa': 'Add New Fatwa',
    'Jurisprudence Solutions': 'Jurisprudence Solutions',
    'Review Questions': 'Review Questions',
    'Pending Inbox': 'Pending Inbox',
    'Add Publication': 'Add Publication',
    'Link Google Drive Files': 'Link Google Drive Files',
    'Pending': 'Pending',

    // Admin Sidebar & Page Titles
    'Manage Articles': 'Manage Articles',
    'Manage Fatwas': 'Manage Fatwas',
    'Manage Questions': 'Manage Questions & Answers',
    'Manage Publications': 'Manage Publications',
    'Manage Lectures': 'Manage Lectures',
    'Manage Events': 'Manage Events',
    'Manage Settings': 'Manage Settings',

    // Form controls and buttons
    'Save Configuration': 'Save Configuration',
    'Saving Settings...': 'Saving Settings...',
    'Cancel': 'Cancel',
    'Save': 'Save',
    'Write Article': 'Write Article',
    'Edit Scholarly Article': 'Edit Scholarly Article',
    'Write New Scholarly Article': 'Write New Scholarly Article',
    'Saving...': 'Saving...',
    'Save Article': 'Save Article',
    'Add Fatwa': 'Add Fatwa',
    'Edit Jurisprudence Fatwa': 'Edit Jurisprudence Fatwa',
    'Add New Jurisprudence Fatwa': 'Add New Jurisprudence Fatwa',
    'Save Fatwa': 'Save Fatwa',
    'Add Lecture': 'Add Lecture',
    'Upload New Audio/Video Lecture': 'Upload New Audio/Video Lecture',
    'Edit Lecture Details': 'Edit Lecture Details',
    'Save Lecture': 'Save Lecture',
    'Add Event': 'Add Event',
    'Create New Scholar Event': 'Create New Scholar Event',
    'Edit Scholar Event': 'Edit Scholar Event',
    'Save Event': 'Save Event',
    'Add Publication Link': 'Add Publication Link',
    'Add New Google Drive Publication': 'Add New Google Drive Publication',
    'Edit Publication Details': 'Edit Publication Details',
    'Save Publication': 'Save Publication',

    // Table headers & Labels
    'Title': 'Title',
    'Category': 'Category',
    'Publish Date': 'Publish Date',
    'Views': 'Views',
    'Actions': 'Actions',
    'Edit Article': 'Edit Article',
    'Delete Article': 'Delete Article',
    'Question Title': 'Question Title',
    'Questioner': 'Questioner',
    'Date Asked': 'Date Asked',
    'Status': 'Status',
    'Answer Question': 'Answer Question',
    'View Details': 'View Details',
    'Delete Question': 'Delete Question',
    'Language': 'Language',
    'Author': 'Author',
    'Download Link': 'Download Link',
    'Edit Publication': 'Edit Publication',
    'Delete Publication': 'Delete Publication',
    'Video/Audio URL': 'Video/Audio URL',
    'Type': 'Type',
    'Edit Lecture': 'Edit Lecture',
    'Delete Lecture': 'Delete Lecture',
    'Event Date': 'Event Date',
    'Location': 'Location',
    'Edit Event': 'Edit Event',
    'Delete Event': 'Delete Event',

    // Manage Settings tab names
    'Biography Details': 'Biography Details',
    'Contact Details': 'Contact Details',
    'Social Networks': 'Social Networks',
    'Home Page Hero': 'Home Page Hero',
    'SEO Settings': 'SEO Settings',
    'Language Settings': 'Language Settings',
    
    // Manage Settings inputs
    'Scholar Full Name': 'Scholar Full Name',
    'Honorary Islamic Title': 'Honorary Islamic Title',
    'Detailed Biography Statement': 'Detailed Biography Statement',
    'Madrasah Education': 'Madrasah Education',
    'University Education': 'University Education',
    'Qualifications (Comma Separated)': 'Qualifications (Comma Separated)',
    'Areas of Expertise (Comma Separated)': 'Areas of Expertise (Comma Separated)',
    'Teaching Experience Synopsis': 'Teaching Experience Synopsis',
    'Research Interests (Comma Separated)': 'Research Interests (Comma Separated)',
    'Associated Institutions (Comma Separated)': 'Associated Institutions (Comma Separated)',
    'Key Achievements (Comma Separated)': 'Key Achievements (Comma Separated)',
    'Office Address': 'Office Address',
    'Phone Number': 'Phone Number',
    'WhatsApp Number Link': 'WhatsApp Number Link',
    'Email Address': 'Email Address',
    'Facebook Profile URL': 'Facebook Profile URL',
    'YouTube Channel URL': 'YouTube Channel URL',
    'Twitter / X URL': 'Twitter / X URL',
    'Instagram URL': 'Instagram URL',
    'Hero Title Name': 'Hero Title Name',
    'Hero Title Designation': 'Hero Title Designation',
    'Hero Introduction Paragraph': 'Hero Introduction Paragraph',
    'Scholar Mission Statement Text': 'Scholar Mission Statement Text',
    'Default Meta Title Tag': 'Default Meta Title Tag',
    'Default Meta Description Tag': 'Default Meta Description Tag',

    // Form inputs placeholders & hints
    'Modify biography profiles, contact numbers, and SEO tags': 'Modify biography profiles, contact numbers, and SEO tags',
    'Choose default system interface language': 'Choose default system interface language',
    'Select Language': 'Select Language',
    'English': 'English',
    'Urdu': 'Urdu',
    'Save Settings': 'Save Settings',

    // Lectures additional
    'Add, update, or remove audio and video sermons': 'Add, update, or remove audio and video sermons',
    'Lecture Title *': 'Lecture Title *',
    'Media Format *': 'Media Format *',
    'Media URL (YouTube/Facebook/MP3 Link) *': 'Media URL (YouTube/Facebook/MP3 Link) *',
    'Custom Thumbnail Image URL (Optional)': 'Custom Thumbnail Image URL (Optional)',
    'Brief Description *': 'Brief Description *',
    'e.g. Purifying the Heart: The Islamic Path': 'e.g. Purifying the Heart: The Islamic Path',
    'Provide a short synopsis overview of the topics discussed in this sermon...': 'Provide a short synopsis overview of the topics discussed in this sermon...',
    'No Lectures Uploaded': 'No Lectures Uploaded',
    'Click the "Add Lecture" button to link your first bayan video/audio.': 'Click the "Add Lecture" button to link your first bayan video/audio.',
    'YouTube Videos': 'YouTube Videos',
    'Facebook Videos': 'Facebook Videos',
    'Audio Lectures': 'Audio Lectures',
    'Bayan Recordings': 'Bayan Recordings',

    // Events additional
    'Add, update, or remove scheduled programs and gatherings': 'Add, update, or remove scheduled programs and gatherings',
    'Add New Event Program': 'Add New Event Program',
    'Edit Event Details': 'Edit Event Details',
    'Event Program Title *': 'Event Program Title *',
    'Event Date & Time *': 'Event Date & Time *',
    'Program Location *': 'Program Location *',
    'Poster Image URL (Optional)': 'Poster Image URL (Optional)',
    'e.g. Halal Investment Workshop Seminar': 'e.g. Halal Investment Workshop Seminar',
    'e.g. Masjid Al-Noor, Seminar Room A': 'e.g. Masjid Al-Noor, Seminar Room A',
    'Provide details about the gathering topics, timings, registration fee if any...': 'Provide details about the gathering topics, timings, registration fee if any...',
    'No Events Scheduled': 'No Events Scheduled',
    'Click the "Add Event" button to schedule your first program.': 'Click the "Add Event" button to schedule your first program.',
  },
  Urdu: {
    // Navigation / Public
    'Home': 'صفحہ اول',
    'About Scholar': 'تعارف سکالر',
    'Articles': 'مقالات',
    'Fatwas': 'فتاویٰ',
    'Q&As': 'سوال و جواب',
    'Publications': 'مطبوعات',
    'Lectures': 'بیانات',
    'Events': 'پروگرام',
    'Contact': 'رابطہ',
    'Ask Question': 'سوال پوچھیں',
    'Ask Q': 'سوال پوچھیں',
    'Dashboard': 'ڈیش بورڈ',
    'Logout': 'لاگ آؤٹ',
    'Admin Login': 'ایڈمن لاگ ان',
    'Navigation': 'نیویگیشن',
    'Switch to Light Mode': 'لائٹ موڈ پر جائیں',
    'Switch to Dark Mode': 'ڈارک موڈ پر جائیں',

    // Branding / Titles
    'Dr. Islamic Scholar': 'ڈاکٹر اسلامی اسکالر',
    'Mufti & Shariah Educator': 'مفتی اور معلمِ شریعت',
    'Mufti & Professor of Islamic Jurisprudence': 'مفتی اور پروفیسر آف اسلامک جیورسپروڈنس',
    'Sheikh & Professor of Islamic Studies': 'شیخ اور پروفیسر آف اسلامک اسٹڈیز',
    'Mufti & Professor of Islamic Law': 'مفتی اور پروفیسر آف اسلامک لا',
    'Professor': 'پروفیسر',

    // Admin Dashboard / General
    'Admin Dashboard': 'ایڈمن ڈیش بورڈ',
    'Welcome back,': 'خوش آمدید،',
    'Website Settings': 'ویب سائٹ سیٹنگز',
    'Total Articles': 'کل مضامین',
    'Total Fatwas': 'کل فتاویٰ',
    'Total Publications': 'کل مطبوعات',
    'Total Lectures': 'کل بیانات',
    'Total Q&As': 'کل سوال و جواب',
    'Total Messages': 'کل پیغامات',
    'Total Website Visitors': 'کل زائرین ویب سائٹ',
    'Quick Content Operations': 'فوری مواد کے آپریشنز',
    'Write New Article': 'نیا مضمون لکھیں',
    'Publish Islamic Rulings': 'اسلامی احکام شائع کریں',
    'Add New Fatwa': 'نیا فتویٰ شامل کریں',
    'Jurisprudence Solutions': 'فقہی مسائل کا حل',
    'Review Questions': 'سوالات کا جائزہ لیں',
    'Pending Inbox': 'پینڈنگ ان باکس',
    'Add Publication': 'مطبوعہ شامل کریں',
    'Link Google Drive Files': 'گوگل ڈرائیو فائلیں لنک کریں',
    'Pending': 'پینڈنگ',

    // Admin Sidebar & Page Titles
    'Manage Articles': 'مضامین کا انتظام',
    'Manage Fatwas': 'فتاویٰ کا انتظام',
    'Manage Questions': 'سوال و جواب کا انتظام',
    'Manage Publications': 'مطبوعات کا انتظام',
    'Manage Lectures': 'بیانات کا انتظام',
    'Manage Events': 'تقریبات کا انتظام',
    'Manage Settings': 'سیٹنگز کا انتظام',

    // Form controls and buttons
    'Save Configuration': 'ترتیبات محفوظ کریں',
    'Saving Settings...': 'محفوظ کیا جا رہا ہے...',
    'Cancel': 'منسوخ کریں',
    'Save': 'محفوظ کریں',
    'Write Article': 'مضمون لکھیں',
    'Edit Scholarly Article': 'علمی مضمون کی ترمیم کریں',
    'Write New Scholarly Article': 'نیا علمی مضمون لکھیں',
    'Saving...': 'محفوظ ہو رہا ہے...',
    'Save Article': 'مضمون محفوظ کریں',
    'Add Fatwa': 'فتویٰ شامل کریں',
    'Edit Jurisprudence Fatwa': 'فقہی فتوے کی ترمیم کریں',
    'Add New Jurisprudence Fatwa': 'نیا فقہی فتویٰ شامل کریں',
    'Save Fatwa': 'فتویٰ محفوظ کریں',
    'Add Lecture': 'بیان شامل کریں',
    'Upload New Audio/Video Lecture': 'نیا آڈیو/ویڈیو بیان اپ لوڈ کریں',
    'Edit Lecture Details': 'بیان کی تفصیلات کی ترمیم کریں',
    'Save Lecture': 'بیان محفوظ کریں',
    'Add Event': 'پروگرام شامل کریں',
    'Create New Scholar Event': 'نیا پروگرام شامل کریں',
    'Edit Scholar Event': 'پروگرام کی ترمیم کریں',
    'Save Event': 'پروگرام محفوظ کریں',
    'Add Publication Link': 'مطبوعہ کا لنک شامل کریں',
    'Add New Google Drive Publication': 'گوگل ڈرائیو کی نئی کتاب شامل کریں',
    'Edit Publication Details': 'کتاب کی تفصیلات کی ترمیم کریں',
    'Save Publication': 'کتاب محفوظ کریں',

    // Table headers & Labels
    'Title': 'عنوان',
    'Category': 'زمرہ',
    'Publish Date': 'تاریخ اشاعت',
    'Views': 'مناظر',
    'Actions': 'اقدامات',
    'Edit Article': 'مضمون ایڈٹ کریں',
    'Delete Article': 'مضمون ڈیلیٹ کریں',
    'Question Title': 'سوال کا عنوان',
    'Questioner': 'سائل کا نام',
    'Date Asked': 'پوچھنے کی تاریخ',
    'Status': 'حالت',
    'Answer Question': 'سوال کا جواب دیں',
    'View Details': 'تفصیلات دیکھیں',
    'Delete Question': 'سوال حذف کریں',
    'Language': 'زبان',
    'Author': 'مصنف',
    'Download Link': 'ڈاؤن لوڈ لنک',
    'Edit Publication': 'کتاب کی ترمیم',
    'Delete Publication': 'کتاب حذف کریں',
    'Video/Audio URL': 'ویڈیو/آڈیو لنک',
    'Type': 'قسم',
    'Edit Lecture': 'بیان ایڈٹ کریں',
    'Delete Lecture': 'بیان حذف کریں',
    'Event Date': 'پروگرام کی تاریخ',
    'Location': 'مقام',
    'Edit Event': 'پروگرام ایڈٹ کریں',
    'Delete Event': 'پروگرام حذف کریں',

    // Manage Settings tab names
    'Biography Details': 'سوانح حیات کی تفصیلات',
    'Contact Details': 'رابطہ کی تفصیلات',
    'Social Networks': 'سوشل نیٹ ورکس',
    'Home Page Hero': 'ہوم پیج ہیرو',
    'SEO Settings': 'ایس ای او سیٹنگز',
    'Language Settings': 'زبان کی ترتیبات',

    // Manage Settings inputs
    'Scholar Full Name': 'سکالر کا پورا نام',
    'Honorary Islamic Title': 'اعزازی اسلامی لقب',
    'Detailed Biography Statement': 'تفصیلی سوانح حیات',
    'Madrasah Education': 'مدرسہ کی تعلیم',
    'University Education': 'یونیورسٹی کی تعلیم',
    'Qualifications (Comma Separated)': 'قابلیت (کوما سے الگ کریں)',
    'Areas of Expertise (Comma Separated)': 'مہارت کے شعبے (کوما سے الگ کریں)',
    'Teaching Experience Synopsis': 'تدریسی تجربہ کا خلاصہ',
    'Research Interests (Comma Separated)': 'تحقیقی دلچسپیاں (کوما سے الگ کریں)',
    'Associated Institutions (Comma Separated)': 'منسلک ادارے (کوما سے الگ کریں)',
    'Key Achievements (Comma Separated)': 'اہم کامیابیاں (کوما سے الگ کریں)',
    'Office Address': 'دفتر کا پتہ',
    'Phone Number': 'فون نمبر',
    'WhatsApp Number Link': 'واٹس ایپ نمبر لنک',
    'Email Address': 'ای میل ایڈریس',
    'Facebook Profile URL': 'فیس بک پروفائل لنک',
    'YouTube Channel URL': 'یوٹیوب چینل لنک',
    'Twitter / X URL': 'ٹویٹر / ایکس لنک',
    'Instagram URL': 'انسٹاگرام لنک',
    'Hero Title Name': 'ہیرو کا نام',
    'Hero Title Designation': 'ہیرو کا عہدہ',
    'Hero Introduction Paragraph': 'ہیرو کا تعارفی پیراگراف',
    'Scholar Mission Statement Text': 'سکالر کا مشن سٹیٹمنٹ',
    'Default Meta Title Tag': 'ڈیفالٹ میٹا ٹائٹل',
    'Default Meta Description Tag': 'ڈیفالٹ میٹا ڈسکرپشن',

    // Form inputs placeholders & hints
    'Modify biography profiles, contact numbers, and SEO tags': 'سوانح حیات، رابطے کے نمبروں اور ایس ای او ٹیگز کی ترمیم کریں',
    'Choose default system interface language': 'سستم انٹرفیس کے لیے پہلے سے طے شدہ زبان کا انتخاب کریں',
    'Select Language': 'زبان منتخب کریں',
    'English': 'انگریزی',
    'Urdu': 'اردو',
    'Save Settings': 'ترتیبات محفوظ کریں',

    // Lectures additional
    'Add, update, or remove audio and video sermons': 'آڈیو اور ویڈیو بیانات کو شامل کریں، اپ ڈیٹ کریں یا حذف کریں',
    'Lecture Title *': 'بیان کا عنوان *',
    'Media Format *': 'میڈیا فارمیٹ *',
    'Media URL (YouTube/Facebook/MP3 Link) *': 'میڈیا لنک (یوٹیوب/فیس بک/ایم پی تھری لنک) *',
    'Custom Thumbnail Image URL (Optional)': 'حسب ضرورت تھمب نیل امیج یو آر ایل (اختیاری)',
    'Brief Description *': 'مختصر تفصیل *',
    'e.g. Purifying the Heart: The Islamic Path': 'مثال کے طور پر: دل کی پاکیزگی: اسلامی طریقہ کار',
    'Provide a short synopsis overview of the topics discussed in this sermon...': 'اس بیان میں زیر بحث موضوعات کا مختصر خلاصہ فراہم کریں...',
    'No Lectures Uploaded': 'کوئی بیان اپ لوڈ نہیں کیا گیا',
    'Click the "Add Lecture" button to link your first bayan video/audio.': 'اپنا پہلا بیان لنک کرنے کے لیے "بیان شامل کریں" بٹن پر کلک کریں۔',
    'YouTube Videos': 'یوٹیوب ویڈیوز',
    'Facebook Videos': 'فیس بک ویڈیوز',
    'Audio Lectures': 'آڈیو بیانات',
    'Bayan Recordings': 'بیانات کی ریکارڈنگ',

    // Events additional
    'Add, update, or remove scheduled programs and gatherings': 'شیڈول پروگراموں اور اجتماعات کو شامل کریں، اپ ڈیٹ کریں یا حذف کریں',
    'Add New Event Program': 'نیا پروگرام شامل کریں',
    'Edit Event Details': 'پروگرام کی تفصیلات ایڈٹ کریں',
    'Event Program Title *': 'پروگرام کا عنوان *',
    'Event Date & Time *': 'پروگرام کی تاریخ اور وقت *',
    'Program Location *': 'پروگرام کا مقام *',
    'Poster Image URL (Optional)': 'پوسٹر امیج یو آر ایل (اختیاری)',
    'e.g. Halal Investment Workshop Seminar': 'مثال کے طور پر: حلال انویسٹمنٹ ورکشاپ سیمینار',
    'e.g. Masjid Al-Noor, Seminar Room A': 'مثال کے طور پر: مسجد النور، سیمینار روم اے',
    'Provide details about the gathering topics, timings, registration fee if any...': 'اجتماع کے موضوعات، اوقات، رجسٹریشن فیس (اگر کوئی ہو) کے بارے میں تفصیلات فراہم کریں...',
    'No Events Scheduled': 'کوئی پروگرام شیڈول نہیں ہے',
    'Click the "Add Event" button to schedule your first program.': 'اپنا پہلا پروگرام شیڈول کرنے کے لیے "پروگرام شامل کریں" بٹن پر کلک کریں۔',

    // Footer & Generic Layout translations
    'Quick Links': 'فوری روابط',
    'Biography & Qualifications': 'سوانح حیات اور اسناد',
    'Scholarly Articles': 'علمی مقالات',
    'Fatwas & Rulings': 'فتاویٰ اور احکام',
    'Questions & Answers': 'سوالات اور جوابات',
    'Books & Studies': 'مطبوعات و کتب',
    'Video & Audio Bayans': 'بیانات (ویڈیو اور آڈیو)',
    'Contact Scholar': 'سکالر سے رابطہ کریں',
    'WhatsApp': 'واٹس ایپ',
    'Stay Updated': 'باخبر رہیں',
    'Subscribe to receive direct notifications when new Islamic articles, publications, or fatwas are posted.': 'جب بھی نئے مضامین، کتب یا فتاویٰ شائع ہوں، تو ان کی براہ راست اطلاع حاصل کرنے کے لیے سبسکرائب کریں۔',
    'Your email address': 'آپ کا ای میل ایڈریس',
    'All Rights Reserved. Derived from classical guidelines.': 'جملہ حقوق محفوظ ہیں۔ کلاسیکی خطوط پر مرتب شدہ۔',
    'Admin Panel': 'ایڈمن پینل',

    // Content cards translations
    'Read Article': 'مضمون پڑھیں',
    'views': 'مناظر',
    'QUESTION:': 'سوال:',
    'RULING SUMMARY:': 'حکم کا خلاصہ:',
    'View Full Ruling': 'مکمل فتویٰ دیکھیں',
    'Watch/Listen Now': 'ابھی دیکھیں/سنیں',
    'Open Original Link': 'اصل لنک کھولیں',
    'By': 'مصنف:',
    'View on Drive': 'گوگل ڈرائیو پر دیکھیں',
    'Download Document': 'کتاب ڈاؤن لوڈ کریں',
    'Upcoming': 'آنے والا پروگرام',
    'Past Event': 'سابقہ پروگرام',

    // Font settings page translations
    'English Font Preference': 'انگریزی فونٹ کی ترجیح',
    'Urdu Font Preference': 'اردو فونٹ کی ترجیح',
    'Select the font style for English content rendering.': 'انگریزی مواد کے لیے اپنی پسندیدہ فونٹ کا انتخاب کریں۔',
    'Select the font style for Urdu content rendering.': 'اردو مواد کے لیے اپنی پسندیدہ فونٹ کا انتخاب کریں۔',
  }
};

export default function useTranslate() {
  const { settings } = useSelector((state) => state.settings);
  const lang = settings?.language || 'English';

  const t = (key, fallback = '') => {
    if (!key) return '';
    return translations[lang]?.[key] || fallback || key;
  };

  return { t, lang, isUrdu: lang === 'Urdu' };
}
